Repository CommunityToolkit/Datasync, pull requests merged in 2024-11, with the labels that each got.

#148 (#143) Remove template warning
  docs/content/setup/server.md
  docs/public/404.html
  docs/public/categories/index.html
  docs/public/css/chroma-auto.css
  docs/public/css/format-print.css
  docs/public/css/print.css
  docs/public/css/swagger.css
  docs/public/css/theme-auto.css
  docs/public/css/variant.css
  docs/public/in-depth/client/auth/index.html
  docs/public/in-depth/client/index.html
  docs/public/in-depth/client/online-operations/index.html
  docs/public/in-depth/index.html
  docs/public/in-depth/server/databases/azuresql/index.html
  docs/public/in-depth/server/databases/cosmos/index.html
  docs/public/in-depth/server/databases/in-memory/index.html
  docs/public/in-depth/server/databases/index.html
  docs/public/in-depth/server/databases/litedb/index.html
  docs/public/in-depth/server/databases/postgresql/index.html
  docs/public/in-depth/server/databases/sqlite/index.html
  docs/public/in-depth/server/index.html
  docs/public/index.html
  docs/public/samples/index.html
  docs/public/samples/server/index.html
  docs/public/samples/todoapp/index.html
  docs/public/samples/todoapp/maui/index.html
  docs/public/samples/todoapp/winui3/index.html
  docs/public/samples/todoapp/wpf/index.html
  docs/public/setup/client/index.html
  docs/public/setup/index.html
  docs/public/setup/index.xml
  docs/public/setup/server/index.html
  docs/public/tags/index.html
Labels: Documentation

#150 (#141) Switch over to centralized package management
  Directory.Packages.props
  samples/Directory.Packages.props
  src/CommunityToolkit.Datasync.Client/CommunityToolkit.Datasync.Client.csproj
  src/CommunityToolkit.Datasync.Server.Abstractions/CommunityToolkit.Datasync.Server.Abstractions.csproj
  src/CommunityToolkit.Datasync.Server.Automapper/CommunityToolkit.Datasync.Server.Automapper.csproj
  src/CommunityToolkit.Datasync.Server.EntityFrameworkCore/CommunityToolkit.Datasync.Server.EntityFrameworkCore.csproj
  src/CommunityToolkit.Datasync.Server.LiteDb/CommunityToolkit.Datasync.Server.LiteDb.csproj
  src/CommunityToolkit.Datasync.Server.NSwag/CommunityToolkit.Datasync.Server.NSwag.csproj
  src/CommunityToolkit.Datasync.Server.Swashbuckle/CommunityToolkit.Datasync.Server.Swashbuckle.csproj
  src/CommunityToolkit.Datasync.Server/CommunityToolkit.Datasync.Server.csproj
  src/Directory.Build.props
  tests/CommunityToolkit.Datasync.Client.Test/CommunityToolkit.Datasync.Client.Test.csproj
  tests/CommunityToolkit.Datasync.Server.EntityFrameworkCore.Test/CommunityToolkit.Datasync.Server.EntityFrameworkCore.Test.csproj
  tests/CommunityToolkit.Datasync.Server.InMemory.Test/CommunityToolkit.Datasync.Server.InMemory.Test.csproj
  tests/CommunityToolkit.Datasync.Server.LiteDb.Test/CommunityToolkit.Datasync.Server.LiteDb.Test.csproj
  tests/CommunityToolkit.Datasync.TestCommon/CommunityToolkit.Datasync.TestCommon.csproj
  tests/CommunityToolkit.Datasync.TestService/CommunityToolkit.Datasync.TestService.csproj
  tests/Directory.Build.props
  tests/EFCore.Packages.props
Labels: Infrastructure

#147 Update OperationsQueueManager.cs
  src/CommunityToolkit.Datasync.Client/Offline/OperationsQueue/OperationsQueueManager.cs
Labels: Client
